apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack
spec:
  selector:
    matchLabels:
      app: full-stack
  replicas: 1
  template:
    metadata:
      labels:
        app: full-stack
    spec:
      containers:
      - name: full-stack-backend
        image: full-stack-backend:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      - name: full-stack-frontend
        image: full-stack-frontend:0.0.1
        imagePullPolicy: Never
        ports:
          - containerPort: 80
