apiVersion: v1
kind: Service
metadata:
  name: full-stack-frontend-service
spec:
  selector:
    app: full-stack
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: full-stack-backend-service
spec:
  selector:
    app: full-stack
  ports:
    - protocol: "TCP"
      port: 8500
      targetPort: 3000
  type: LoadBalancer