version: '3.4'

services:
  chugong-database:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - chugong-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_PASSWORD: "root"
      MONGO_INITDB_USERNAME: "root"
      MONGO_INITDB_DATABASE: "chugong"
volumes:
  chugong-data:
